apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  selector:
    matchLabels:
      type: app
    replica: 2
    strategy:
      type: RollingUpdate
     minReadSeconds: 10
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: mynginx
        image: nginx       
        ports:
        - containerPort: 80
