apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
spec:
  selector:
    matchLabels:
      app: recreate
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - name: recreate
        image: nginx
        ports:
        - containerPort: 80
