apiVersion: v1
kind: Service
metadata:
  name: rolling-update
  labels:
    app: mynginx
spec:
  selector:
    app: mynginx
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 80
